---
title: "analysis"
author: "Patrick"
date: "4/19/2023"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(readxl)
library(openxlsx)
library(tidycensus)
library(janitor)
library(gt)

knitr::opts_chunk$set(echo = TRUE)
```

Read in data for municipalities and MSAs
```{r}

munis <- read_csv("https://github.com/mtmleczko/nzlud/raw/main/nzlud_muni.csv", col_types = cols(GEOID = col_character())) %>%
  mutate(GEOID = str_pad(as.character(GEOID), "left", width = 7, pad = "0"))
  
msas <- read_csv("https://github.com/mtmleczko/nzlud/raw/main/nzlud_msa.csv", col_types = cols(cbsa10 = col_character()))

msa_coverage <- read_csv("https://github.com/mtmleczko/nzlud/raw/main/msa_coverage_rates.csv", col_types = cols(cbsa10 = col_character()))

msas <- left_join(msas, msa_coverage, by = "cbsa10")

github_link <- "https://github.com/mtmleczko/nzlud/raw/main/ZRI_expand_muni_up.xlsx"
library(httr)
temp_file <- tempfile(fileext = ".xlsx")
req <- GET(github_link, 
          # authenticate using GITHUB_PAT
           authenticate(Sys.getenv("GITHUB_PAT"), ""),
          # write result to disk
           write_disk(path = temp_file))
zri_up <- readxl::read_excel(temp_file) %>% 
  filter(!is.na(zri_up_st)) %>% 
  mutate(zri_quint = ntile(zri_up_st, 5))

regions <- read_csv("state-geocodes-v2016.csv", skip = 5) %>% 
  clean_names() %>% 
  mutate(region_name = case_when(
    region == 1 ~ "Northeast",
    region == 2 ~ "Midwest",
    region == 3 ~ "South",
    region == 4 ~ "West",
  )) %>% 
  select(state_fips, region_name)

options(scipen = 999)

```

```{r}
#https://www.census.gov/programs-surveys/ces/data/public-use-data/opportunity-atlas-data-tables.html
opportunity <- read_csv("tract_kfr_rP_gP_p25.csv",
                        col_types = cols(tract = col_character()))

opportunity2 <- read_csv("tract_kfr_top20_rP_gP_p25.csv",
                        col_types = cols(tract = col_character()))

opportunity_clean <- opportunity %>% 
  left_join(opportunity2) %>% 
  clean_names() %>% 
  mutate(opp_code = str_pad(tract, "left", pad = "0", width = 11)) %>% 
  select(-tract)
  
```


Recreate EV blog table

```{r}

top10_msa <- msas %>% 
  filter(responses >= 10) %>%  #only those that coded 10 or more municipalities
  arrange(desc(zri_full_st)) %>% 
  head(10) %>% 
  mutate(rank = row_number()) %>% 
  select(rank, cbsaname10, zri_full_st)

write_csv(top10_msa, "top10_msa.csv")

```

Least Restrictive MSAs

```{r}

bottom10_msa <- msas %>% 
  filter(responses >= 10) %>%  #only those that coded 10 or more municipalities
  arrange(zri_full_st) %>% 
  head(10) %>% 
  mutate(rank = row_number()) %>% 
  select(rank, cbsaname10, zri_full_st)

write_csv(top10_msa, "bottom10_msa.csv")

```


```{r}
upsai <- read_csv("UPSAI_050820.csv")

tracts_places_xwalk <- read_csv("2010tracts-2010places-xwalk.csv", skip = 1, col_types = cols(.default = "c")) %>% clean_names() %>% 
  mutate(state_code = str_pad(state_code, "left", pad = "0", width = 2),
         county_code = str_sub(county_code, start = -3, end = -1),
         tract_mid = ifelse(grepl("\\.", tract), tract, paste0(tract, "00")),
         tract_code = str_pad(str_remove_all(tract_mid, "\\."), width = 6, side = "left", pad = "0"),
         state_place = paste0(state_code,str_pad(place_code, "left", pad = "0", width = 5)),
         afact = as.numeric(placefp_to_tract_allocation_factor),
         opp_code = paste0(state_code, county_code, tract_code),
         population_2010 = as.numeric(population_2010)) %>% 
  left_join(opportunity_clean, by = "opp_code")

countysubs_places_xwalk <- read_csv("2010tracts-2010csubs-xwalk.csv", skip = 1, col_types = cols(.default = "c")) %>% clean_names() %>% 
  mutate(countysub_code = str_pad(county_subdivision_code, "left", pad = "0", width = 5),
         state_code = str_sub(str_pad(county_code, "left", pad = "0", width = 5), start = 1, end = 2),
         county_code = str_sub(county_code, start = -3, end = -1),
         tract_mid = ifelse(grepl("\\.", tract), tract, paste0(tract, "00")),
         tract_code = str_pad(str_remove_all(tract_mid, "\\."), width = 6, side = "left", pad = "0"),
         state_csub = paste0(state_code, countysub_code),
         afact = as.numeric(cousubfp_to_tract_allocation_factor),
         opp_code = paste0(state_code, county_code, tract_code),
         population_2010 = as.numeric(population_2010))%>% 
  left_join(opportunity_clean, by = "opp_code")

csubs_places_xwalked <- bind_rows(tracts_places_xwalk, countysubs_places_xwalk)

rural_munis <- left_join(csubs_places_xwalked, upsai, by = c("state_code"= "STATEFP", "county_code"= "COUNTYFP", "tract_code" = "TRACTCE")) %>% 
  mutate(GEOID = if_else(is.na(state_place), state_csub, state_place)) %>% 
  group_by(GEOID) %>% 
  summarize(urban_prob_weighted = sum(afact*UPSAI_urban, na.rm = T),
            suburban_prob_weighted = sum(afact*UPSAI_suburban, na.rm = T),
            rural_prob_weighted = sum(afact*UPSAI_rural, na.rm = T),
            opp_income = sum(household_income_at_age_35_r_p_g_p_p25*population_2010/sum(population_2010, na.rm = T), na.rm = T),
            afact_check = sum(afact),
            state_code = first(state_code)) %>% 
    mutate(max_column = case_when(
    urban_prob_weighted >= suburban_prob_weighted &  urban_prob_weighted >= rural_prob_weighted ~ "urban",
    suburban_prob_weighted >= urban_prob_weighted & suburban_prob_weighted >= rural_prob_weighted ~ "suburban",
    rural_prob_weighted >= urban_prob_weighted & rural_prob_weighted >= suburban_prob_weighted ~ "rural"
    )) %>% 
  left_join(regions, by = c("state_code"= "state_fips"))
  

```


Census data for places
```{r}

vars <- load_variables(2019, "acs5")

place <- get_acs(
  geography = "place",
  survey = "acs5",
  variables = c(total_population = "B01003_001",
                median_household_income = "B19019_001",
                race_eth_denom = "B03002_001",
                white_nonhsp = "B03002_003",
                education_denom = "B15003_001",
                bachelors = "B15003_022",
                masters = "B15003_023",
                professional = "B15003_024",
                doctoral = "B15003_025"
                ),
  year = 2019,
  output = "wide"
) %>% 
  mutate(bachelor_per = (bachelorsE + mastersE + professionalE + doctoralE)/education_denomE)

# place_data <- place %>% 
#   mutate(white_quint = ntile((white_nonhspE/race_eth_denomE), 5),
#          hh_inc_quint = ntile(median_household_incomeE, 5),
#          )

countysub <- get_acs(
  state = state.abb,
  geography = "county subdivision",
  survey = "acs5",
  variables = c(total_population = "B01003_001",
                median_household_income = "B19019_001",
                race_eth_denom = "B03002_001",
                white_nonhsp = "B03002_003",
                education_denom = "B15003_001",
                bachelors = "B15003_022",
                masters = "B15003_023",
                professional = "B15003_024",
                doctoral = "B15003_025"
                ),
  year = 2019,
  output = "wide"
) %>%  mutate(
  GEOID = paste0(str_sub(GEOID, start = 1, end = 2), str_sub(GEOID, start = 6, end = 10)),
  bachelor_per = (bachelorsE + mastersE + professionalE + doctoralE)/education_denomE)


place_countysub <- bind_rows(place, countysub) %>% 
  mutate(
    non_white = race_eth_denomE - white_nonhspE,
    ice = (white_nonhspE - non_white)/(race_eth_denomE)
  )

msa_census <- get_acs(geography = "cbsa",
               survey = "acs5",
  variables = c(total_population = "B01003_001",
                median_household_income = "B19019_001",
                race_eth_denom = "B03002_001",
                white_nonhsp = "B03002_003"
                ),
  year = 2019,
  output = "wide") %>% 
  mutate(white_quint = ntile((white_nonhspE/race_eth_denomE), 5),
         hh_inc_quint = ntile(median_household_incomeE, 5)
         )

```

```{r}

munis_rural_census <- munis %>% 
  left_join(place_countysub, by = "GEOID") %>% 
  left_join(rural_munis, by = "GEOID") %>% 
  mutate(mf_quintile = ntile(mf_per, 5))

anti_join(munis, place_countysub, by = c("GEOID"))
anti_join(munis, rural_munis, by = "GEOID")

```

Get top restricive munis

```{r}
top10_munis <- munis %>% 
  arrange(desc(zri_st)) %>% 
  #head(10) %>% 
  mutate(rank = row_number()) %>% 
  select(rank, statename, place, zri_st)

bottom10_munis <- munis %>% 
  arrange(zri_st) %>% 
  #head(10) %>% 
  mutate(rank = row_number()) %>% 
  select(rank, statename, place, zri_st)
  
```


```{r}

munis_rural_census %>% 
  mutate(zri_quint = ntile(zri_st, 5)) %>% 
  filter(max_column == "suburban") %>% 
  ggplot()+
  geom_point(mapping = aes(x = zri, y = ice))

```



```{r}

munis_rural_census %>% 
  mutate(zri_quint = ntile(zri_st, 5)) %>% 
  ggplot()+
  geom_bar(mapping = aes(x = zri_quint, fill = max_column), position = "fill")


```



```{r}

munis_by_suburb <- munis_rural_census %>% 
  group_by(max_column) %>% 
  summarize(no_places = n(),
            avg_pop = mean(total_populationE, na.rm = T),
            white_proportion = mean(white_nonhspE/race_eth_denomE, na.rm = T),
            hh_inc = mean(median_household_incomeE, na.rm = T),
            ed = mean(bachelor_per, na.rm = T),
            zri = mean(zri, na.rm = T),
            mf_per = mean(mf_per, na.rm = T)
            )

munis_by_suburb %>% 
  ggplot()+
  geom_col(mapping = aes(x = factor(max_column, levels = rev(c("rural", "urban", "suburban"))), y = zri, fill = max_column))+
  coord_flip() +
  theme_minimal()+
  labs(title = "Suburbs Have More Restrictive Zoning",
       subtitle = "Average ZRI scores by municipality type",
       x = element_blank(),
       y = "ZRI")+
  guides(fill = guide_legend((title = element_blank())))

munis_by_suburb %>% select(zri, max_column) %>%  write_csv("munis_by_municipality_type.csv")


```

```{r}

munis_by_suburb_region <- munis_rural_census %>% 
  group_by(max_column, region_name) %>% 
  summarize(no_places = n(),
            avg_pop = mean(total_populationE, na.rm = T),
            white_proportion = mean(white_nonhspE/race_eth_denomE, na.rm = T),
            hh_inc = mean(median_household_incomeE, na.rm = T),
            ed = mean(bachelor_per, na.rm = T),
            zri = mean(zri, na.rm = T),
            mf_per = mean(mf_per, na.rm = T)
            )

munis_by_suburb_region %>% 
  ggplot()+
  geom_col(mapping = aes(x = region_name, y = zri, fill = max_column), 
           position = "dodge")

```

```{r}

munis_by_zri <- munis_rural_census %>% 
  mutate(zri_quint = ntile(zri_st, 5)) %>% 
  group_by(zri_quint) %>% 
  summarize(no_places = n(),
            avg_pop = mean(total_populationE, na.rm = T),
            white_proportion = mean(white_nonhspE/race_eth_denomE, na.rm = T),
            hh_inc = mean(median_household_incomeE, na.rm = T),
            ed = mean(bachelor_per, na.rm = T),
            zri = mean(zri_st, na.rm = T),
            mf_per = mean(mf_per, na.rm = T),
            opp_income = mean(opp_income, na.rm = T)
            )


munis_by_zri %>% 
  ggplot()+
  geom_col(mapping = aes(x = zri_quint, y = opp_income, fill = zri_quint))





```

```{r}

model <- lm(median_household_incomeE ~ zri, data = munis_rural_census)

summary(model)

model <- lm(opp_income ~ zri, data = munis_rural_census)

summary(model)
```


```{r}

munis_by_mf<-munis_rural_census %>% 
  group_by(mf_quintile) %>% 
  summarize(no_places = n(),
            avg_pop = mean(total_populationE, na.rm = T),
            white_proportion = mean(white_nonhspE/race_eth_denomE, na.rm = T),
            hh_inc = mean(median_household_incomeE, na.rm = T),
            ed = mean(bachelor_per, na.rm = T),
            zri = mean(zri_st, na.rm = T),
            mf_per = mean(mf_per, na.rm = T)
            )

munis_by_mf %>% 
  ggplot()+
  geom_col(mapping = aes(x = mf_quintile, y = white_proportion, fill = mf_quintile))


```





```{r}

msas_census <- left_join(msas, msa_census, by = c("cbsa10" = "GEOID")) %>% 
  mutate(zri_quint = ntile(zri_full_st, 5),
    non_white = race_eth_denomE - white_nonhspE,
    ice = (white_nonhspE - non_white)/(race_eth_denomE)
  )

```

```{r}

msas_census   %>% 
  group_by(white_quint) %>% 
  summarize(no_places = n(),
            avg_pop = mean(total_populationE, na.rm = T),
            white_proportion = mean(white_nonhspE/race_eth_denomE, na.rm = T),
            hh_inc = mean(median_household_incomeE, na.rm = T),
            zri = mean(zri_full_st, na.rm = T),
            )

msas_census   %>% 
  group_by(hh_inc_quint) %>% 
  summarize(no_places = n(),
            avg_pop = mean(total_populationE, na.rm = T),
            white_proportion = mean(white_nonhspE/race_eth_denomE, na.rm = T),
            hh_inc = mean(median_household_incomeE, na.rm = T),
            zri = mean(zri_full_st, na.rm = T),
            )

msas_census %>% 
  group_by(zri_quint) %>% 
    summarize(no_places = n(),
            avg_pop = mean(total_populationE, na.rm = T),
            white_proportion = mean(white_nonhspE/race_eth_denomE, na.rm = T),
            hh_inc = mean(median_household_incomeE, na.rm = T),
            zri = mean(zri_full_st, na.rm = T),
            )

```

```{r}
msas_census %>%   
  filter(responses >= 10, total_populationE >= 500000) %>% 
  ggplot(mapping = aes(x = median_household_incomeE, y = zri_full_st))+
  geom_point()+
  geom_smooth(method = lm, se = F) +
  theme_minimal()+
  labs(title = "Wealthier Metropolitan Areas Have More Restrictive Zoning Policies",
       x = "Median household income",
       y = "ZRI")

msas_census %>%   
  filter(responses >= 10, total_populationE >= 500000) %>% 
  select(cbsaname10, zri_full_st, median_household_incomeE) %>% 
  write.csv("median_income_zri_cbsa.csv")

```

```{r}
top20 <- msas_census %>%   
  filter(responses >= 10, total_populationE >= 500000, coverage_rate > .15) %>% 
  mutate(cbsaname10 = str_replace_all(cbsaname10," Metropolitan Statistical Area| Metropolitan Statistical","")) %>% 
  arrange(desc(zri_full_st)) %>% 
  head(20) %>% 
  select("Metro" = cbsaname10, "Percent of Municipalities Covered" = coverage_rate, "ZRI" = zri_full_st)

top20 %>% 
  write.csv("top20_cbsa.csv")

top20 %>% 
  gt() %>% 
  fmt_percent(columns = "Percent of Municipalities Covered",  decimals = 0) %>% 
  fmt_number(columns = "ZRI", decimals = 2)



```



```{r}
msas_census %>%   
  filter(responses >= 10) %>% 
  ggplot(mapping = aes(x = ice, y = zri_full_st))+
  geom_point()+
  geom_smooth(method = lm)
```


```{r}

munis_rural_census %>% 
  mutate(zri_quint = ntile(zri_st, 5)) %>% 
  group_by(zri_quint, max_column) %>% 
      summarize(no_places = n(),
            avg_pop = mean(total_populationE, na.rm = T),
            white_proportion = mean(white_nonhspE/race_eth_denomE, na.rm = T),
            hh_inc = mean(median_household_incomeE, na.rm = T)
            )


```

